### ISSUE TITLE
Make UIs for a screen

### ISSUE THREAD

**Issue by hiashutoshsingh** [hiashutoshsingh/FlutterOneWeekChallenge#1]
Make UIs for a screen

**Comment by AkashdeepDas** [comment]
Hey can you assign me with this?

**Comment by hiashutoshsingh** [comment]
@AkashdeepDas Hey Akash this is open for all, you just have a create a PR with a design in flutter you like and that can help others to get started.

**Comment by rahul975337** [comment]
please add hacktoberfest-accepted label it would be a great help to me
