### ISSUE TITLE
i am facing a probelm

### ISSUE THREAD

**Issue by vipuluthaiah** [hiashutoshsingh/FlutterOneWeekChallenge#8]
![image](https://user-images.githubusercontent.com/45168922/96551032-58116f80-12cf-11eb-88cf-33d544da1c26.png)
![image](https://user-images.githubusercontent.com/45168922/96551064-6495c800-12cf-11eb-98f1-87398477b1ef.png)
why is  it showing its on
review period?

**Comment by hiashutoshsingh** [comment]
Please read the hackobferst rules @vipuluthaiah

**Comment by vipuluthaiah** [comment]
i did check..but they said
Labeling a pull request ‘hacktoberfest-accepted’
is it imp?

**Comment by vipuluthaiah** [comment]
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are labeled as ‘hacktoberfest-accepted’ by a maintainer, or submitted in a repository classified with the ‘hacktoberfest’ topic. Pull requests in repositories with the ‘hacktoberfest’ topic will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.

To put the rules in a form consistent with the spirit of Hacktoberfest:
https://hacktoberfest.digitalocean.com/hacktoberfest-update
i am confused the pr i submitted to ur repo was is labled?and is it a a valid?

**Comment by vipuluthaiah** [comment]
am new to this...But i am lil confused i did contribute to u r repo!
but if the repo is not labled hacktoberfest-accepted or hacktoberfest does it still count as vaild pr?
